
Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-20.04"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :vmware_desktop do |v|
    v.memory = 256
    v.linked_clone = true
  end

  ## App Server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "172.16.10.4"
  end
  
  ## App Server 2
  config.vm.define "app2" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip: "172.16.10.5"
  end
  
  ## Database Server 
  config.vm.define "db" do |db|
    db.vm.hostname = "orc-db.test"
    db.vm.network :private_network, ip: "172.16.10.6"
  end
end
