
# Vagrant.configure("2") do |config|
#   config.vm.box = "gyptazy/ubuntu22.04-arm64"

#   config.ssh.insert_key = false

#   config.vm.synced_folder ".", "/vagrant", disabled: true

#   # config.vm.provider :vmware_desktop do |v|
#   #   # v.gui = true
#   #   v.memory = 512
#   #   v.linked_clone = true
#   # end

#   # config.vm.define "moot" do |app|
#   #   app.vm.hostname = "moot.test"
#   #   app.vm.network :private_network, ip: "192.168.225.110"
#   # end
# end
