# ---
# - name: Install Apache.
#   hosts: all
#   become: true

#   tasks:
#     - name: Install Apache.
#       ansible.builtin.package:
#         name:
#           - httpd
#           - httpd-devel
#         state: present
#     - name: Copy configuration files.
#       copy:
#         src: "{{ item.src }}"
#         dest: "{{ item.dest }}"
#         owner: root
#         group: root
#         mode: 0644
#       with_items:
#         - src: httpd.conf
#           dest: /etc/httpd/conf/httpd.conf
#         - src: httpd-vhosts
#           dest: /etc/httpd/conf/httpd-vhosts.conf
    
#     - name: Ensure apache is started and configure it to run at boot.
#       service:
#         name: httpd
#         state:  started
#         enabled:  true