# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "gyptazy/rocky9.3-arm64"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :vmware_desktop do |v|
    # v.gui = true
    v.memory = 512
    v.linked_clone = true
  end

  config.vm.define "moot" do |app|
    app.vm.hostname = "moot.test"
    app.vm.network :private_network, ip: "192.168.225.110"
  end
end
